### ISSUE TITLE
Move Megamenu to Zo2HtmlMenu

### ISSUE THREAD

**Issue by jooservices** [cleversoft/Zo2-Joomla-Template-Framework#227]
Zo2HtmlMenu
- mega
- offcanvas

We will allow to render menu by use
zo2Html::_('menu','mega',<any_config_if_need>)
zo2Html::_('menu','offcanvas',<any_config_if_need>)
It will call to
Zo2HtmlMenu->mega(); All config will declare here or receive from func args
Zo2HtmlMenu->offcanvas(); All config will declare here or receive from func args

**Comment by soulevilx** [comment]
Concept is changed in v2
