### ISSUE TITLE
Structure less files

### ISSUE THREAD

**Issue by jooservices** [cleversoft/Zo2-Joomla-Template-Framework#242]
- template.less
-- @import modules.less ( style for modules )
-- @import extensions.less ( style for Joomla! core extensions )
-- @import typo.less ( custom typography )
-- @import joomla.less ( Joomla! core styles )
-- @import <ext>_<name>.less ( for 3rd extensions supported ). Optional based on each template feature.

For current exists less files, please provide some document to know purpose of each file

**Comment by soulevilx** [comment]
Applied for v2
