### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by hitman47h** [cleversoft/Zo2-Joomla-Template-Framework#285]
Sometimes when i open mainpage i see Fatal error: Class 'ZtExtension' not found in /var/www/vhosts/**mysite**/httpdocs/plugins/system/zooframework/core/includes/framework.php on line 42
If i refresh then there is not this error and site work fine.

**Comment by phuongnd** [comment]
Hello,

Please give us more detail about your system! 
- Joomla version? 
- Zo2 version? 
- PHP version? 
  ... 

As I can see you are using very older framework for Joomla 1.x! And it was discontinued. 

Kind regards

**Comment by hitman47h** [comment]
I installed this http://www.zootemplate.com/joomla/templates/zt-construction-joomla-building-template
PHP Version 5.5.30
Joomla! Version 3.4.7 Stable
zo2 Current version: 1.4.8

**Comment by hitman47h** [comment]
it stable on 3.4.7 now i made update to 3.4.8 and error appeared
