### ISSUE TITLE
Canvas menu not working

### ISSUE THREAD

**Issue by phuongnd** [cleversoft/Zo2-Joomla-Template-Framework#288]
When you go to Global Configuration >> System
Find the “Cache Settings” section
Set “Cache” to “ON - Conservative caching” or “ON - Progressive caching” 
and any changes in the template manager then canvas menu can't work.

**Comment by soulevilx** [comment]
https://github.com/cleversoft/Zo2-Joomla-Template-Framework/pull/289
Please check and review than merging.

**Comment by phuongnd** [comment]
it works! Thank you
