### ISSUE TITLE
Something error with language support 

### ISSUE THREAD

**Issue by thanhppm** [cleversoft/Zo2-Joomla-Template-Framework#299]
By the way, I found another little bug in all your joomla templates.
If you want to ensure follow these steps:
start firefox
start any demo, for example http://zt-finance.zoodemo.com/index.php/en/
start built-in tool “Inspect Element”, by using right mouse botton, for watching html code of the pages.
In the first line of the html code your can see next code;
<html lang="en-gb" dir="ltr">
Now change the site language to arabic. 
Apparently, the first line must become <html lang="ar-aa" dir="rtl">
But it is still <html lang="en-gb" dir="ltr">

Now change the site language to english. 
And you can see the code became <html lang="ar-aa" dir="rtl">
In spite the english language of the page.
If you want the code matches the language, you must reload the page or click any menu item or link.
Now it becomes <html lang="en-gb" dir="ltr">
I think this little bug originates from Zo2 Framework plagin.
When it is enabled, function $this->zo2->template->getLanguage() does not work correctly as well as function $this->language.
It may well be a problem for developers.
Partly the bug with the code in the first line can be solved by using other function:
<?php $CurrentLanguage = JFactory::getLanguage();?>
<?php $lang = mb_strtolower($CurrentLanguage->getTag());?>
…
<?php echo $lang; ?>
Instead of the:
<?php echo $this->zo2->template->getLanguage(); ?>

**Comment by alexs7777** [comment]
The title is not quite accurate. Not 

> RTL language support

But just 

> language support

Because this bug happens with any other language, not only arabic.

**Comment by phuongnd** [comment]
Hello alexs7777,

If you check the default zo2 quickstart package, you will see that it's working well. 

You should upgrade your language package to latest version in order to solve that issue. 

Kind regards

**Comment by alexs7777** [comment]
Ok. Thanks.
Maybе you should upgrade all demo your site too))

**Comment by phuongnd** [comment]
@alexs7777 thanks so much for reporting this issue. We've fixed it, fyi please check [this commit](https://github.com/cleversoft/Zo2-Joomla-Template-Framework/commit/019d6b20f1e076e9173ab46a5fa8ed36f810edf5)
